version: '3.9'


services:
 # MongoDB services
  mongo_db:
   container_name: db_container
   image: mongo:latest
   restart: always
   volumes:
     - mongo_db:/data/lb

  # Node API services
  api:
    build: .
    ports:
       - 8080:8080
    environment:
      PORT: 8080
      MONGO_URL: mongodb://mongo_db
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}

